# 01 Data audit
Thin narrative over `src.services.quality`. Every value comes from `reports/dq_report.json`, produced by `sql/02_data_quality.sql` and `src/data/validation.py` in `make build`.

In [1]:
import logging, sys
from pathlib import Path
ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(ROOT))
logging.getLogger("streamlit").setLevel(logging.ERROR)
import pandas as pd
pd.set_option("display.width", 160); pd.set_option("display.max_columns", 20)

## Data-quality rules
Each rule has a status. Problems are shown, not hidden.

In [2]:
from src.services import quality
checks = quality.checks()
print(quality.summary())
checks[['group', 'check', 'value', 'rule', 'status']]

2026-10-04 20:32:30.813 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

2026-10-04 20:32:30.816 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

2026-10-04 20:32:30.817 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

{'PASS': 19, 'WARNING': 7, 'FAIL': 0}

             group                                              check      value                                               rule   status
0           Volume                                   Application rows   438557.0                                                > 0     PASS
1           Volume                                        Credit rows  1048575.0                                                > 0     PASS
2           Volume                                  Unique applicants   438510.0                                                > 0     PASS
3           Volume                              Unique credit clients    45985.0                                                > 0     PASS
4          Linkage                       Matched clients (both files)    36457.0                                                > 0     PASS
5          Linkage                   Credit clients with demographics   0.792802                                >= 75% else WARNING     PASS
6          Linkage                     Applicants with credit history   0.083138                  informational; low rate = WARNING  WARNING
7       Uniqueness               Duplicate (ID, month) in credit file        0.0                                                = 0     PASS
8       Uniqueness                         Duplicated application IDs       47.0              = 0 else WARNING (kept once, flagged)  WARNING
9         Validity                              Invalid status values        0.0                                                = 0     PASS
10        Validity                    Null ID or month in credit file        0.0                                                = 0     PASS
11        Validity                                        Month range   -60 to 0                           max = 0 (relative index)     PASS
12      Continuity                 Month gaps within client histories        0.0           = 0 else WARNING (gaps are never filled)     PASS
13         History                              Single-record clients      399.0                                      informational     PASS
14         History                  Clients with fewer than 6 records     5216.0                                      informational     PASS
15         History                 Clients observed for all 61 months      222.0                                      informational     PASS
16         History  Clients whose first record is X (leading dorma...   0.407459                                <= 25% else WARNING  WARNING
17         History               Clients that are never open (X only)     4536.0                                      informational     PASS
18        Maturity   Immature vintages (fewer than 12 observable MOB)         12                                      informational  WARNING
19       Semantics                        C returns to an open status        1.0                    <= 0.1% of transitions out of C     PASS
20       Semantics                Dormant (X) exits that later return   0.538537                                      informational     PASS
21       Semantics          Charge-off (5) followed by a non-5 status   0.068414                                 <= 5% else WARNING  WARNING
22      Truncation           credit_record.csv cut at Excel row limit      fired  row count = Excel limit and hard ID cut => WAR...  WARNING
23      Truncation               Left truncation of earliest vintages  not fired         early MOB-0 mix or size pile-up => WARNING     PASS
24  Missing values                            OCCUPATION_TYPE missing    0.30601                                      informational     PASS
25  Missing values                      DAYS_EMPLOYED sentinel 365243    75329.0                                        set to NULL  WARNING

## Recomputed audit values vs the pilot targets in the brief

In [3]:
rec = quality.pilot_reconciliation()
print(f"{int(rec.agrees.sum())} of {len(rec)} items agree exactly")
rec

29 of 29 items agree exactly

                            item      pilot   computed  difference  agrees
0                    credit_rows  1048575.0  1048575.0         0.0    True
1                 credit_clients    45985.0    45985.0         0.0    True
2            credit_dup_id_month        0.0        0.0         0.0    True
3                      month_min      -60.0      -60.0         0.0    True
4                      month_max        0.0        0.0         0.0    True
5                month_gap_pairs        0.0        0.0         0.0    True
6                matched_clients    36457.0    36457.0         0.0    True
7               application_only   402053.0   402053.0         0.0    True
8                    credit_only     9528.0     9528.0         0.0    True
9         first_status_x_clients    18737.0    18737.0         0.0    True
10        first_status_0_clients    26802.0    26802.0         0.0    True
11        first_status_c_clients      432.0      432.0         0.0    True
12                        c_to_c   419323.0   419323.0         0.0    True
13           c_transitions_total   419324.0   419324.0         0.0    True
14            c_preceded_by_open    20241.0    20241.0         0.0    True
15            open_preceded_by_c        1.0        1.0         0.0    True
16             active_to_x_exits    27660.0    27660.0         0.0    True
17           active_to_x_clients    12183.0    12183.0         0.0    True
18         x_to_active_reentries    19930.0    19930.0         0.0    True
19           x_to_active_clients     6561.0     6561.0         0.0    True
20  co_to_nonco_consecutive_nonx      107.0      107.0         0.0    True
21           co_transitions_nonx     1564.0     1564.0         0.0    True
22              open_accounts_m0     9318.0     9318.0         0.0    True
23              open_accounts_m1    10769.0    10769.0         0.0    True
24                       nonx_m1    28273.0    28273.0         0.0    True
25                x_only_clients     4536.0     4536.0         0.0    True
26           new_co_12m_from_m12       41.0       41.0         0.0    True
27               open_0_4_at_m12     9554.0     9554.0         0.0    True
28           vintage_m60_clients      231.0      231.0         0.0    True

## File truncation
The credit file has exactly Excel's row limit. The test checks whether the ID-sorted file is cut.

In [4]:
tr = quality.report()['truncation']
{k: tr[k] for k in ['row_count', 'excel_row_limit', 'app_ids_above_cut', 'app_ids_above_cut_matched', 'app_ids_at_or_below_cut', 'app_ids_at_or_below_cut_matched', 'final_client_first_status_is_c', 'fired', 'excluded']}

{'row_count': 1048575,
 'excel_row_limit': 1048575,
 'app_ids_above_cut': 402053.0,
 'app_ids_above_cut_matched': 0.0,
 'app_ids_at_or_below_cut': 36457.0,
 'app_ids_at_or_below_cut_matched': 36457.0,
 'final_client_first_status_is_c': True,
 'fired': True,
 'excluded': True}

## New charge-offs within 12 months by origin
These small counts shape the validation design.

In [5]:
pd.DataFrame(quality.report()['new_chargeoffs'])

   ORIGIN  open_0_4  new_co_12m
0     -36      5954          29
1     -30      6770          34
2     -24      7674          34
3     -18      8664          37
4     -12      9554          41